_G.dots = {
	UI = {
		icons = {
			diagnostics = {
				ERROR = "",
				WARN = "",
				HINT = "",
				INFO = "",
			},
			misc = {
				bug = "",
				ellipsis = "…",
				git = "",
				search = "",
				vertical_bar = "│",
			},
			symbol_kinds = {
				Array = "󰅪",
				Class = "",
				Color = "󰏘",
				Constant = "󰏿",
				Constructor = "",
				Enum = "",
				EnumMember = "",
				Event = "",
				Field = "󰜢",
				File = "󰈙",
				Folder = "󰉋",
				Function = "󰆧",
				Interface = "",
				Keyword = "󰌋",
				Method = "󰆧",
				Module = "",
				Operator = "󰆕",
				Property = "󰜢",
				Reference = "󰈇",
				Snippet = "",
				Struct = "",
				Text = "",
				TypeParameter = "",
				Unit = "",
				Value = "",
				Variable = "󰀫",
			},
		},
	},
}
